# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

# Common configuration shared between services:

x-volume-checkout-service: &volume-checkout-service
  type: "volume"
  source: "checkout"
  target: "/usr/local/src/project-structure"

x-service: &service
  user: "${PUID:-1000}:${PGID:-${PUID:-1000}}"
  environment:
    TZ: "${TZ:-Etc/UTC}"
  volumes:
    - <<: *volume-checkout-service
  working_dir: "/usr/local/src/project-structure${WORKTREE_REL:-}"

x-service-linter: &service-linter
  <<: *service
  profiles:
    - "lint"

# Override `$ docker compose` configuration for development or testing here in this
# repository checkout. Put everything used outside this checkout in
# `./compose.yml`.
services:
  reuse:
    <<: *service-linter
    image: "docker.io/fsfe/reuse${DOCKER_REUSE_DIGEST:-:latest-debian}"
    command: >-
      lint

  # https://github.com/hadolint/hadolint#how-to-use
  hadolint:
    <<: *service-linter
    # For this and other development tools in container images, define the image tag to
    # follow when upgrading as the default and `./.env` controls the specific digest
    # used currently:
    image: "ghcr.io/hadolint/hadolint${DOCKER_HADOLINT_DIGEST:-:latest-debian}"
    command: >-
      hadolint "./build-host/Dockerfile"

  vale:
    <<: *service-linter
    image: "docker.io/jdkato/vale${DOCKER_VALE_DIGEST:-:latest}"
    command: >-
      .

  ## Containers for simulating CI/CD:

  build-host:
    <<: *service
    image: "${DOCKER_NAMESPACE:-merpatterson}/project-structure:build-host"
    profiles:
      - "ci"
    build:
      context: "./build-host/"
      args:
        BUILDKIT_INLINE_CACHE: "1"
        USER_SIGNINGKEY: "${USER_SIGNINGKEY:-}"
      cache_from:
        - "${DOCKER_NAMESPACE:-merpatterson}/project-structure:build-host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - <<: *volume-checkout-service
      - "${CHECKOUT_DIR:-.}${WORKTREE_REL:-}/build-host/container\
        /usr/local/bin/init-job.sh\
        :/usr/local/bin/init-job.sh"
      - "${CHECKOUT_DIR:-.}${WORKTREE_REL:-}/build-host/container\
        /usr/local/bin/entrypoint.sh\
        :/usr/local/bin/entrypoint.sh"
      # Share local authentication inside the container:
      - "~/.ssh/:/home/runner/.ssh/"
      - "${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}\
        :${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}"
      - "~/.gnupg/:/home/runner/.gnupg/"
      - "/run/user/${PUID:-1000}/gnupg/S.gpg-agent:/home/runner/.gnupg/S.gpg-agent"
    env_file: "./.env"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${DOCKER_GID:-${PGID:-${PUID:-1000}}}"
      SSH_AUTH_SOCK: "${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}"
      # Pass the bind volume source paths along as seen from the host `# dockerd`:
      CHECKOUT_DIR: "${CHECKOUT_DIR:-.}"
      WORKTREE_REL: "${WORKTREE_REL:-}"
      # DEBUG: "true"
    user: "0:0"
    command: >-
      make -j -O release-all

volumes:
  checkout:
    name: "project_structure_checkout"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${CHECKOUT_DIR:-.}/"
