# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

# Minimal `$ docker compose` configuration to show the requirements for running
# project-structure in containers.

services:
  ## Container for use by end users:
  project-structure:
    image: "merpatterson/project-structure"
    container_name: "project-structure"
    environment:
      # Match the time zone of the host through `./.env`:
      TZ: "${TZ:-Etc/UTC}"
      # Make the runtime user configurable in `./.env` to match permissions inside and
      # outside the container.  Default to the common/standard main/first user and group
      # IDs
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
    restart: "unless-stopped"
    volumes:
      # Preserve user configuration, data, and caches between containers and variants:
      - type: "volume"
        source: "project_home"
        target: "/home/project-structure"
        volume:
          subpath: "./.config/"
      - type: "volume"
        source: "project_home"
        target: "/home/project-structure"
        volume:
          subpath: "./.local/share/"
      - type: "volume"
        source: "project_home"
        target: "/home/project-structure"
        volume:
          subpath: "./.cache/"

volumes:
  # Share user `${HOME}` data between services but isolated within the project:
  project_home:
    name: "${PROJECT_NAME:-project-structure}_home"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${CHECKOUT_DIR:-.}/home/"
